# Redis server credentials. If no password/username is required, type "null"
redis:
  hostname: localhost
  port: 6379
  username: null
  password: null
  ssl: false

# Name of the current server. Shall be unique across the network!
serverIdentifier: MySuperServer1

# Names of the channels to subscribe on start. Can be empty as plugins can manually subscribe on their own.
# For detailed information see our GitHub: https://github.com/ForestTechMC/ForestRedisAPI
channels:
  - bkpcommands
  - my_channel

# This section is used to process commands from selected redis channels.
commands:

  # Only command reception is supported
  receive:
    enabled: false
    list:
      - enabled: true
        # You'll also  need to add this channel to the subscribed channels above
        channel: bkpcommands
        # Available modes:
        # ALL
        # WHITELIST_HARD - check command and arguments
        # WHITELIST_SOFT - only check command, not arguments
        # BLACKLIST_HARD - check command and arguments
        # BLACKLIST_SOFT - nly check command, not arguments
        allow: WHITELIST_SOFT
        list:
          - say
          - save-off
          - save-all
          - save-on

      - enabled: false
        channel: other_commands
        allow: ALL
        list: []